-- ms_compiler (Visual Macro Compiler) --
    return function(ms)

        local dataDir    = ms.profile.path("data")
        local jsonPath   = ms.profile.file("visualJson")
        local luaPath    = ms.profile.file("visualLua")
        local STAMP      = "-- AUTO-GENERATED by ms.compiler v3 (DO NOT EDIT BY HAND) --"

        ms.compiler = {}

        -- Broken-macro quarantine --
            ms._brokenMacro = function(spec)
                spec = type(spec) == "table" and spec or {}
                local id = spec.id
                if type(id) ~= "string" then return end
                local label  = spec.name or id
                local errMsg = spec.err or "unknown compile error"
                local fn = ms.fn(function()
                    ms.alert("Macro '" .. label .. "' has a build error and "
                        .. "can't run. Open the builder to fix it.", 4)
                    error("[ms.compiler] macro '" .. id
                        .. "' failed to compile: " .. errMsg, 0)
                end, label)
                local opts = {
                    group = spec.group or "visual",
                    label = label,
                }
                if spec.cooldown then opts.cooldown = spec.cooldown end
                local b = spec.bind
                if type(b) == "table" and (b.type or b.key) then
                    opts.default = {
                        type = b.type or "key",
                        mods = b.mods or {},
                        key  = b.key,
                    }
                end
                ms.bind.define(id, fn, opts)
            end
        -- END Broken-macro quarantine --

        -- Helpers --
            local function toolRef(val)
                if type(val) ~= "table" then return nil end
                if type(val.__toolRef) == "string"
                    and val.__toolRef:match("^[%a_][%w_]*$") then
                    return 'ms.settings.get("' .. val.__toolRef .. '")'
                end
                if type(val.__varRef) == "string"
                    and val.__varRef:match("^[%a_][%w_]*$") then
                    return 'ms.vars.get("' .. val.__varRef .. '")'
                end
                return nil
            end

            local function interpString(s)
                if not s:match("{[%a_][%w_]*}") then
                    return string.format("%q", s)
                end
                local parts, lit = {}, {}
                local function flushLit()
                    if #lit > 0 then
                        parts[#parts + 1] = string.format("%q", table.concat(lit))
                        lit = {}
                    end
                end
                local i, n = 1, #s
                while i <= n do
                    local c = s:sub(i, i)
                    if c == "{" and s:sub(i + 1, i + 1) == "{" then
                        lit[#lit + 1] = "{"
                        i = i + 2
                    elseif c == "}" and s:sub(i + 1, i + 1) == "}" then
                        lit[#lit + 1] = "}"
                        i = i + 2
                    elseif c == "{" then
                        local close = s:find("}", i + 1, true)
                        local name = close and s:sub(i + 1, close - 1) or nil
                        if name and name:match("^[%a_][%w_]*$") then
                            flushLit()
                            parts[#parts + 1] = 'tostring(ms.vars.get("' .. name .. '") or "")'
                            i = close + 1
                        else
                            lit[#lit + 1] = "{"
                            i = i + 1
                        end
                    else
                        lit[#lit + 1] = c
                        i = i + 1
                    end
                end
                flushLit()
                if #parts == 0 then return '""' end
                if #parts == 1 then return parts[1] end
                return "(" .. table.concat(parts, " .. ") .. ")"
            end

            local function serialize(val)
                local ref = toolRef(val)
                if ref then return "ms.interp(" .. ref .. ")" end
                local t = type(val)
                if t == "string"  then return interpString(val) end
                if t == "number"  then return tostring(val) end
                if t == "boolean" then return tostring(val) end
                if t == "nil"     then return "nil" end
                if t == "table" then
                    local parts = {}
                    local isList = (#val > 0)
                    if isList then
                        for _, v in ipairs(val) do
                            parts[#parts + 1] = serialize(v)
                        end
                    else
                        for k, v in pairs(val) do
                            local key
                            if type(k) == "string" and k:match("^%a[%w_]*$") then
                                key = k
                            else
                                key = "[" .. serialize(k) .. "]"
                            end
                            parts[#parts + 1] = key .. " = " .. serialize(v)
                        end
                    end
                    return "{" .. table.concat(parts, ", ") .. "}"
                end
                return tostring(val)
            end

            local function ident(v, default)
                if v == nil or v == "" then return default end
                return v
            end

            local function numArg(v, default)
                local ref = toolRef(v)
                if ref then return ref end
                if type(v) == "number" then return tostring(v) end
                if type(v) == "string" and v ~= "" and tonumber(v) then return v end
                return tostring(default)
            end

            local ARG_ORDER = {
                ["ms.toggle"] = {
                    "key",
                    "mods",
                },
                ["ms.multiPress"] = {
                    "keys",
                    "delayMs",
                    "mods",
                },
                ["ms.randWait"] = {
                    "min",
                    "max",
                },
                ["ms.jitter"] = {
                    "base",
                    "jitterMs",
                },
                ["ms.waitApp"] = {
                    "appName",
                    "timeout",
                },
                ["ms.waitNotApp"] = {
                    "appName",
                    "timeout",
                },
                ["ms.window"] = {
                    "operation",
                    "x",
                    "y",
                    "w",
                    "h",
                },
                ["ms.windowPos"] = {
                    "appName",
                },
                ["ms.pixelColor"] = {
                    "x",
                    "y",
                    "reference",
                },
                ["ms.pixelMatch"] = {
                    "x",
                    "y",
                    "reference",
                    "color",
                    "tolerance",
                },
                ["ms.waitPixel"] = {
                    "x",
                    "y",
                    "ref",
                    "color",
                    "tolerance",
                    "timeout",
                },
                ["ms.waitNotPixel"] = {
                    "x",
                    "y",
                    "ref",
                    "color",
                    "tolerance",
                    "timeout",
                },
                ["ms.ocr"] = {
                    "x",
                    "y",
                    "w",
                    "h",
                },
                ["ms.readNumber"] = {
                    "x",
                    "y",
                    "w",
                    "h",
                },
                ["ms.findText"] = {
                    "text",
                    "x",
                    "y",
                    "w",
                    "h",
                },
                ["ms.waitText"] = {
                    "text",
                    "x",
                    "y",
                    "w",
                    "h",
                    "timeout",
                },
                ["ms.appRunning"] = {
                    "appName",
                },
                ["ms.appIsFront"] = {
                    "appName",
                },
                ["ms.focus"] = {
                    "appName",
                },
                ["ms.keystate"] = {
                    "key",
                },
                ["ms.bindstate"] = {
                    "id",
                },
                ["ms.flick"] = {
                    "dx",
                    "dy",
                },
                ["ms.cam.sweepBlocking"] = {
                    "dx",
                    "dy",
                    "durationMs",
                },
                ["ms.mousestate"] = {
                    "button",
                },
                ["ms.padstate"] = {
                    "button",
                },
                ["ms.padaxis"] = {
                    "axis",
                },
                ["ms.pause"] = {
                    "macro",
                },
                ["ms.resume"] = {
                    "macro",
                },
                ["ms.playSlot"] = {
                    "slotId",
                },
                ["ms.setVolume"] = {
                    "level",
                },
                ["ms.screenshot"] = {
                    "path",
                },
                ["ms.notify"] = {
                    "title",
                    "subTitle",
                    "infoText",
                },
                ["ms.cancelMacros"] = {
                    "macro",
                },
            }

            local function buildArgs(params, argOrder)
                if not params or not argOrder then return "" end
                if params.color == nil and type(params.r) == "number"
                    and type(params.g) == "number" and type(params.b) == "number" then
                    params.color = string.format("#%02X%02X%02X", params.r, params.g, params.b)
                end
                local parts = {}
                local last = 0
                for i, key in ipairs(argOrder) do
                    local v = params[key]
                    if v == "" then v = nil end
                    if v ~= nil then last = i end
                    parts[i] = v == nil and "nil" or serialize(v)
                end
                return table.concat(parts, ", ", 1, last)
            end
        -- END Helpers --

        -- Emitters --
            local INDENT = "    "

            local function indent(n)
                local s = ""
                for _ = 1, n do s = s .. INDENT end
                return s
            end

            local emitStep

            local emitters = {}

            local function optNum(v)
                local ref = toolRef(v)
                if ref then return ref end
                local n = tonumber(v)
                if n and n > 0 then return tostring(n) end
                return nil
            end

            local function keyArgs(p, extra)
                local hasMods = type(p.mods) == "table" and #p.mods > 0
                local args = serialize(p.key)
                if hasMods or extra then
                    args = args .. ", " .. (hasMods and serialize(p.mods) or "nil")
                end
                if extra then args = args .. ", " .. extra end
                return args
            end

            local currentMacroId

            emitters["ms.type"] = function(step, lvl)
                local p = step.params or {}
                return indent(lvl) .. "ms.type(" .. keyArgs(p, optNum(p.hold)) .. ")"
            end

            emitters["ms.wait"] = function(step, lvl)
                local p = step.params or {}
                return indent(lvl) .. "ms.wait(" .. numArg(p.ms, 100) .. ")"
            end

            emitters["ms.copy"] = function(step, lvl)
                local text = (step.params and step.params.text) or ""
                return indent(lvl) .. "ms.copy(" .. serialize(text) .. ")"
            end

            emitters["ms.paste"] = function(step, lvl)
                return indent(lvl) .. "ms.paste()"
            end

            emitters["ms.press"] = function(step, lvl)
                local p = step.params or {}
                local args
                if p.mods and #p.mods > 0 then
                    args = serialize(p.key) .. ", " .. serialize(p.mods)
                else
                    args = serialize(p.key)
                end
                return indent(lvl) .. "ms.press(" .. args .. ")"
            end

            emitters["ms.hold"] = function(step, lvl)
                local p = step.params or {}
                return indent(lvl) .. "ms.hold(" .. keyArgs(p, optNum(p.duration)) .. ")"
            end

            emitters["ms.release"] = function(step, lvl)
                local p = step.params or {}
                local args = keyArgs({
                    key  = p.key or "",
                    mods = p.mods,
                })

                return indent(lvl) .. "ms.release(" .. args .. ")"
            end

            emitters["ms.sound"] = function(step, lvl)
                local p = step.params or {}
                local wait = p.async == true or p.async == "true"
                local device = p.device ~= nil and p.device ~= ""
                local args = serialize(p.path or "")
                if wait or device then
                    args = args .. ", " .. (wait and "false" or "nil")
                end
                if device then
                    args = args .. ", " .. serialize(p.device)
                end
                return indent(lvl) .. "ms.sound(" .. args .. ")"
            end

            emitters["ms.setMacros"] = function(step, lvl)
                local p = step.params or {}
                local on = p.state == true or p.state == "on" or (tonumber(p.state) or 0) ~= 0
                local args = on and "1" or "0"
                if p.silent == true then args = args .. ", true" end
                return indent(lvl) .. "ms.setMacros(" .. args .. ")"
            end

            emitters["ms.done"] = function(step, lvl)
                local p = step.params or {}
                local id
                if type(p.macro) == "string" and p.macro ~= "" then
                    id = serialize(p.macro)
                elseif currentMacroId then
                    id = serialize(currentMacroId)
                else
                    id = "(function() local c = ms._coroContext[coroutine.running()]"
                        .. " local l = c and c.callStack and c.callStack[1]"
                        .. " l = l and l:gsub(\"^test:\", \"\")"
                        .. " if l and (ms.registry._defs or {})[l] then return l end"
                        .. " for d, def in pairs(ms.registry._defs or {}) do"
                        .. " if def.label == l then return d end end end)()"
                end
                return indent(lvl) .. "ms.done(" .. id .. ")"
            end

            emitters["ms.cam"] = function(step, lvl)
                local p = step.params or {}
                return indent(lvl) .. "ms.cam(" .. numArg(p.dx, 0) .. ", " .. numArg(p.dy, 0) .. ")"
            end

            emitters["ms.scroll"] = function(step, lvl)
                local p = step.params or {}
                local dir = serialize(p.direction or "up")
                if toolRef(p.clicks) then
                    return indent(lvl) .. "ms.scroll(" .. dir .. ", " .. numArg(p.clicks, 1) .. ")"
                end
                if p.clicks and p.clicks > 1 then
                    return indent(lvl) .. "ms.scroll(" .. dir .. ", " .. tostring(p.clicks) .. ")"
                end
                return indent(lvl) .. "ms.scroll(" .. dir .. ")"
            end

            emitters["ms.alert"] = function(step, lvl)
                local p = step.params or {}
                local args = serialize(p.message or p.msg or "")
                if tonumber(p.duration) then args = args .. ", " .. tostring(tonumber(p.duration) / 1000) end
                return indent(lvl) .. "ms.alert(" .. args .. ")"
            end

            emitters["ms.Mouse"] = function(step, lvl)
                local p = step.params or {}
                local parts = {}
                parts[#parts + 1] = serialize(p.operation or "Click")
                parts[#parts + 1] = serialize(p.button or "Left")
                parts[#parts + 1] = serialize(p.reference or "Mouse")
                local x1 = p.x1 ~= nil and p.x1 or p.x
                local y1 = p.y1 ~= nil and p.y1 or p.y
                parts[#parts + 1] = numArg(x1, 0)
                parts[#parts + 1] = numArg(y1, 0)
                local op = tostring(p.operation or ""):lower()
                local hold = numArg(p.hold, 50)
                if op == "drag" or p.x2 ~= nil or p.y2 ~= nil or hold ~= "50" then
                    parts[#parts + 1] = numArg(p.x2, 0)
                    parts[#parts + 1] = numArg(p.y2, 0)
                end
                if hold ~= "50" then parts[#parts + 1] = hold end
                return indent(lvl) .. "ms.Mouse(" .. table.concat(parts, ", ") .. ")"
            end

            emitters["ms.moveMouse"] = function(step, lvl)
                local p = step.params or {}
                local x   = numArg(p.x, 0)
                local y   = numArg(p.y, 0)
                local ref = serialize(p.ref or p.reference or "Absolute")
                local dur = numArg(p.durationMs, 200)
                return indent(lvl) .. "ms.moveMouse("
                    .. x .. ", " .. y .. ", " .. ref .. ", " .. dur .. ")"
            end

            emitters["ms.dragPath"] = function(step, lvl)
                local p = step.params or {}
                local pts   = serialize(p.points or "")
                local btn   = serialize(p.button or "Left")
                local ref   = serialize(p.ref or p.reference or "Absolute")
                local delay = numArg(p.delayMs, 10)
                return indent(lvl) .. "ms.dragPath("
                    .. pts .. ", " .. btn .. ", " .. ref .. ", " .. delay .. ")"
            end

            emitters["var_set"] = function(step, lvl)
                local p = step.params or {}
                local value = serialize(p.value)
                if type(p.name) == "string" and p.name:match("^[%a_][%w_]*$") then
                    return indent(lvl) .. p.name .. " = " .. value
                end
                return indent(lvl) .. "local " .. ident(p.name, "v") .. " = " .. value
            end

            emitters["call_fn"] = function(step, lvl)
                local p = step.params or {}
                local name = type(p.name) == "string"
                    and p.name:match("^[%a_][%w_]*$") or nil
                if not name then
                    return indent(lvl) .. "-- call function (unresolved reference)"
                end
                return indent(lvl) .. 'ms.callFn("' .. name .. '")'
            end

            emitters["hvar_set"] = function(step, lvl)
                local p = step.params or {}
                local name = type(p.name) == "string"
                    and p.name:match("^[%a_][%w_]*$") or nil
                if not name then
                    return indent(lvl) .. "-- set helper var (unresolved reference)"
                end
                return indent(lvl) .. 'ms.vars.set("' .. name .. '", '
                    .. serialize(p.value) .. ")"
            end

            emitters["ms.switchProfile"] = function(step, lvl)
                local p = step.params or {}
                return indent(lvl) .. "ms.switchProfile(" .. serialize(p.name or "") .. ")"
            end

            emitters["ms.switchPack"] = function(step, lvl)
                local p = step.params or {}
                local kind = tostring(p.kind or "macro")
                if kind ~= "macro" and kind ~= "theme" and kind ~= "sound" then
                    kind = "macro"
                end
                return indent(lvl) .. "ms.switchPack(" .. serialize(p.slug or "")
                    .. ', "' .. kind .. '")'
            end

            emitters["var_add"] = function(step, lvl)
                local p = step.params or {}
                local name   = ident(p.name, "v")
                return indent(lvl) .. name .. " = " .. name .. " + " .. numArg(p.amount, 1)
            end

            emitters["var_sub"] = function(step, lvl)
                local p = step.params or {}
                local name   = ident(p.name, "v")
                return indent(lvl) .. name .. " = " .. name .. " - " .. numArg(p.amount, 1)
            end

            emitters["var_mul"] = function(step, lvl)
                local p = step.params or {}
                local name   = ident(p.name, "v")
                return indent(lvl) .. name .. " = " .. name .. " * " .. numArg(p.amount, 2)
            end

            local _flowCounter = 0

            local _actionDelay = 0

            local _loopDepth = 0

            local _CONTAINER = {
                ["if"]     = true,
                ["for"]    = true,
                ["while"]  = true,
                ["repeat"] = true,
            }

            local function interpExpr(s)
                return (s:gsub("{([%a_][%w_]*)}", 'ms.vars.get("%1")'))
            end

            local function hasWait(steps)
                for _, st in ipairs(steps or {}) do
                    if st.action == "ms.wait" then return true end
                    if hasWait(st.body) or hasWait(st["then"]) or hasWait(st["else"]) then return true end
                end
                return false
            end

            local function stepCond(step)
                local c = step.condition
                if c == nil then c = step.params and step.params.condition end
                local ref = toolRef(c)
                if ref then return ref end
                if type(c) == "table" then c = nil end
                if c == nil or c == "" then c = "true" end
                return interpExpr(c)
            end

            local function thenSteps(step) return step["then"] or step.then_steps end
            local function elseSteps(step) return step["else"] or step.else_steps end

            local VAR_ACTIONS = {
                var_set = true,
                var_add = true,
                var_sub = true,
                var_mul = true,
            }
            local function collectTempVars(steps, seen, order)
                if type(steps) ~= "table" then return end
                for _, step in ipairs(steps) do
                    if VAR_ACTIONS[step.action] then
                        local nm = step.params and step.params.name
                        if type(nm) == "string" and nm:match("^[%a_][%w_]*$")
                            and not seen[nm] then
                            seen[nm] = true
                            order[#order + 1] = nm
                        end
                    end
                    collectTempVars(thenSteps(step), seen, order)
                    collectTempVars(elseSteps(step), seen, order)
                    collectTempVars(step.body, seen, order)
                end
            end

            local function tempVarDecl(steps)
                local seen, order = {}, {}
                collectTempVars(steps, seen, order)
                if #order == 0 then return nil end
                local zeros = {}
                for i = 1, #order do zeros[i] = "0" end
                return indent(1) .. "local " .. table.concat(order, ", ")
                    .. " = " .. table.concat(zeros, ", ")
            end

            emitters["if"] = function(step, lvl)
                local cond = stepCond(step)
                local lines = {}
                lines[#lines + 1] = indent(lvl) .. "if " .. cond .. " then"
                lines[#lines + 1] = indent(lvl + 1) .. "ms.log('if', '" .. cond:gsub("'", "\\'") .. "', true)"
                local ts = thenSteps(step)
                if ts then
                    for _, s in ipairs(ts) do
                        lines[#lines + 1] = emitStep(s, lvl + 1)
                    end
                end
                local es = elseSteps(step)
                if es and #es > 0 then
                    lines[#lines + 1] = indent(lvl) .. "else"
                    lines[#lines + 1] = indent(lvl + 1) .. "ms.log('if', '" .. cond:gsub("'", "\\'") .. "', false)"
                    for _, s in ipairs(es) do
                        lines[#lines + 1] = emitStep(s, lvl + 1)
                    end
                end
                lines[#lines + 1] = indent(lvl) .. "end"
                return table.concat(lines, "\n")
            end

            emitters["for"] = function(step, lvl)
                local p = step.params or {}
                local varName = ident(p.var, "i")
                local from    = p.from or 1
                local to      = p.to or 1
                local stepVal = p.step
                local lines = {}
                local forArgs = tostring(from) .. ", " .. tostring(to)
                if stepVal then forArgs = forArgs .. ", " .. tostring(stepVal) end
                _flowCounter = _flowCounter + 1
                local fc = "_fc" .. _flowCounter
                lines[#lines + 1] = indent(lvl) .. "local " .. fc .. " = 0"
                lines[#lines + 1] = indent(lvl) .. "for " .. varName .. " = " .. forArgs .. " do"
                lines[#lines + 1] = indent(lvl + 1) .. fc .. " = " .. fc .. " + 1"
                _loopDepth = _loopDepth + 1
                if step.body then
                    for _, s in ipairs(step.body) do
                        lines[#lines + 1] = emitStep(s, lvl + 1)
                    end
                end
                _loopDepth = _loopDepth - 1
                lines[#lines + 1] = indent(lvl) .. "end"
                lines[#lines + 1] = indent(lvl) .. "ms.log('for', '" .. varName .. "=" .. forArgs .. "', " .. fc .. ")"
                return table.concat(lines, "\n")
            end

            emitters["while"] = function(step, lvl)
                local cond = stepCond(step)
                local lines = {}
                _flowCounter = _flowCounter + 1
                local fc = "_fc" .. _flowCounter
                lines[#lines + 1] = indent(lvl) .. "local " .. fc .. " = 0"
                lines[#lines + 1] = indent(lvl) .. "while " .. cond .. " do"
                lines[#lines + 1] = indent(lvl + 1) .. fc .. " = " .. fc .. " + 1"
                _loopDepth = _loopDepth + 1
                if step.body then
                    for _, s in ipairs(step.body) do
                        lines[#lines + 1] = emitStep(s, lvl + 1)
                    end
                end
                _loopDepth = _loopDepth - 1
                if not hasWait(step.body) then lines[#lines + 1] = indent(lvl + 1) .. "ms.wait(0)" end
                lines[#lines + 1] = indent(lvl) .. "end"
                lines[#lines + 1] = indent(lvl) .. "ms.log('while', " .. string.format("%q", cond) .. ", " .. fc .. ")"
                return table.concat(lines, "\n")
            end

            emitters["repeat"] = function(step, lvl)
                local cond = stepCond(step)
                local lines = {}
                _flowCounter = _flowCounter + 1
                local fc = "_fc" .. _flowCounter
                lines[#lines + 1] = indent(lvl) .. "local " .. fc .. " = 0"
                lines[#lines + 1] = indent(lvl) .. "repeat"
                lines[#lines + 1] = indent(lvl + 1) .. fc .. " = " .. fc .. " + 1"
                _loopDepth = _loopDepth + 1
                if step.body then
                    for _, s in ipairs(step.body) do
                        lines[#lines + 1] = emitStep(s, lvl + 1)
                    end
                end
                _loopDepth = _loopDepth - 1
                if not hasWait(step.body) then lines[#lines + 1] = indent(lvl + 1) .. "ms.wait(0)" end
                local count = tonumber(cond)
                if count then
                    lines[#lines + 1] = indent(lvl) .. "until " .. fc .. " >= " .. math.max(1, math.floor(count))
                else
                    lines[#lines + 1] = indent(lvl) .. "until " .. cond
                end
                lines[#lines + 1] = indent(lvl) .. "ms.log('repeat', " .. string.format("%q", cond) .. ", " .. fc .. ")"
                return table.concat(lines, "\n")
            end

            emitters["break"] = function(step, lvl)
                if _loopDepth > 0 then return indent(lvl) .. "do break end" end
                return indent(lvl) .. "do return end"
            end

            emitters["comment"] = function(step, lvl)
                local text = tostring((step.params and step.params.text) or "")
                local out = {}
                for line in (text .. "\n"):gmatch("([^\n]*)\n") do
                    out[#out + 1] = indent(lvl) .. "-- " .. line:gsub("\r", "")
                end
                return table.concat(out, "\n")
            end

            emitters["code"] = function(step, lvl)
                local src = (step.params and step.params.source) or ""
                local lines = {}
                for line in src:gmatch("([^\n]*)\n?") do
                    if line ~= "" then
                        lines[#lines + 1] = indent(lvl) .. line
                    end
                end
                return table.concat(lines, "\n")
            end

            emitters["setting"] = function(step, lvl)
                local p = step.params or {}
                local key = type(p.key) == "string"
                    and p.key:match("^[%a_][%w_]*$") or nil
                if not key then
                    return indent(lvl) .. "-- setting (unresolved reference)"
                end
                local label = type(p.label) == "string"
                    and p.label:gsub("[\r\n]", " ") or key
                return indent(lvl) .. '-- setting "' .. label
                    .. '" (shared, read via ms.settings.get("' .. key .. '"))'
            end

            local function genericEmitter(step, lvl)
                local action = step.action
                local p = step.params or {}
                if ARG_ORDER[action] then
                    return indent(lvl) .. action .. "(" .. buildArgs(p, ARG_ORDER[action]) .. ")"
                end
                local block = ms._builderIndex and ms._builderIndex[action]
                local order = block and block._argOrder
                if not order and type(step.argOrder) == "table" then order = step.argOrder end
                if order then
                    return indent(lvl) .. action .. "(" .. buildArgs(p, order) .. ")"
                end
                if p.args then
                    local parts = {}
                    for _, v in ipairs(p.args) do
                        parts[#parts + 1] = serialize(v)
                    end
                    return indent(lvl) .. action .. "(" .. table.concat(parts, ", ") .. ")"
                end
                local parts = {}
                for k, v in pairs(p) do
                    parts[#parts + 1] = k .. "=" .. serialize(v)
                end
                if #parts == 0 then
                    return indent(lvl) .. action .. "()"
                end
                return indent(lvl) .. action .. "(" .. serialize(p) .. ")"
            end

            emitters["action_delay"] = function(step, lvl)
                local p = step.params or {}
                local n = tonumber(p.delayMs) or 0
                if n < 0 then n = 0 end
                _actionDelay = math.floor(n)
                return indent(lvl) .. "-- action delay: " .. _actionDelay
                    .. "ms between steps"
            end

            emitStep = function(step, lvl)
                lvl = lvl or 1
                local action = step.action
                if not action then return indent(lvl) .. "-- [empty step]" end
                local emitter = emitters[action]
                local line = emitter and emitter(step, lvl) or genericEmitter(step, lvl)
                if _actionDelay > 0 and action ~= "action_delay"
                    and not _CONTAINER[action] then
                    line = line .. "\n" .. indent(lvl)
                        .. "ms.wait(" .. _actionDelay .. ")"
                end
                return line
            end
        -- END Emitters --

        -- Compile --
            ms.compiler.compile = function(macroDef)
                assert(type(macroDef) == "table", "ms.compiler.compile: macroDef must be a table")
                assert(type(macroDef.id) == "string", "ms.compiler.compile: macroDef.id must be a string")

                local id     = macroDef.id
                local name   = macroDef.name or id
                local author = macroDef.author or "Visual"
                local group  = macroDef.group or "visual"
                local steps  = macroDef.steps or {}
                local bind   = macroDef.bind or {}
                local cooldown = macroDef.cooldown
                local shared = macroDef.shared
                if type(shared) == "string" then
                    shared = shared:gsub('[%z\1-\31"\\]', ""):gsub("^%s+", ""):gsub("%s+$", "")
                    if shared == "" then shared = nil end
                else
                    shared = nil
                end

                assert(id:match("^[%a_][%w_]*$"),
                    "ms.compiler.compile: invalid macro id '" .. id .. "' (must be a valid Lua identifier)")

                local fnName = id .. "Function"
                local lines = {}

                lines[#lines + 1] = "local " .. fnName .. " = ms.fn(function()"
                lines[#lines + 1] = indent(1) .. "local t = 100"
                local tvDecl = tempVarDecl(steps)
                if tvDecl then lines[#lines + 1] = tvDecl end
                _actionDelay = 0
                _loopDepth = 0
                local prevMacroId = currentMacroId
                currentMacroId = id
                local emitOk, emitErr = pcall(function()
                    for _, step in ipairs(steps) do
                        lines[#lines + 1] = emitStep(step, 1)
                    end
                end)
                currentMacroId = prevMacroId
                if not emitOk then error(emitErr, 0) end
                lines[#lines + 1] = "end, " .. string.format("%q", name) .. ")"
                lines[#lines + 1] = ""

                lines[#lines + 1] = 'ms.bind.define("' .. id .. '", ' .. fnName .. ", {"
                lines[#lines + 1] = indent(1) .. "group   = " .. string.format("%q", group) .. ","
                lines[#lines + 1] = indent(1) .. "label   = " .. string.format("%q", name) .. ","
                if cooldown then
                    lines[#lines + 1] = indent(1) .. "cooldown = " .. tostring(cooldown) .. ","
                end
                if shared then
                    lines[#lines + 1] = indent(1) .. 'shared  = "' .. shared .. '",'
                end
                if bind.type or bind.key then
                    lines[#lines + 1] = indent(1) .. "default = {"
                    lines[#lines + 1] = indent(2) .. "type = " .. string.format("%q", bind.type or "key") .. ","
                    if bind.mods and #bind.mods > 0 then
                        local modParts = {}
                        for _, m in ipairs(bind.mods) do modParts[#modParts + 1] = string.format("%q", m) end
                        lines[#lines + 1] = indent(2) .. "mods = {" .. table.concat(modParts, ", ") .. "},"
                    else
                        lines[#lines + 1] = indent(2) .. "mods = {},"
                    end
                    if bind.key then
                        lines[#lines + 1] = indent(2) .. "key  = " .. string.format("%q", bind.key) .. ","
                    end
                    lines[#lines + 1] = indent(1) .. "},"
                end
                lines[#lines + 1] = "})"

                return table.concat(lines, "\n")
            end

            ms.compiler.compileFunction = function(fnDef)
                assert(type(fnDef) == "table", "ms.compiler.compileFunction: fnDef must be a table")
                assert(type(fnDef.id) == "string", "ms.compiler.compileFunction: fnDef.id must be a string")
                assert(fnDef.id:match("^[%a_][%w_]*$"),
                    "ms.compiler.compileFunction: invalid id '" .. fnDef.id .. "'")

                local id    = fnDef.id
                local label = fnDef.name or id
                local steps = fnDef.steps or {}
                local fnName = id .. "Tool"
                local lines = {}

                local asCoroutine = fnDef.coroutine ~= false
                local secondArg = asCoroutine
                    and ('"' .. label:gsub('[\r\n"]', " ") .. '"')
                    or "false"

                lines[#lines + 1] = "local " .. fnName .. " = ms.fn(function()"
                lines[#lines + 1] = indent(1) .. "local t = 100"
                local tvDecl = tempVarDecl(steps)
                if tvDecl then lines[#lines + 1] = tvDecl end
                _actionDelay = 0
                _loopDepth = 0
                currentMacroId = nil
                for _, step in ipairs(steps) do
                    lines[#lines + 1] = emitStep(step, 1)
                end
                lines[#lines + 1] = "end, " .. secondArg .. ")"
                lines[#lines + 1] = ""
                lines[#lines + 1] = 'ms.fn.define("' .. id .. '", ' .. fnName .. ", {"
                lines[#lines + 1] = indent(1) .. 'group = "tool",'
                lines[#lines + 1] = indent(1) .. 'label = "' .. label:gsub('[\r\n"]', " ") .. '",'
                lines[#lines + 1] = "})"

                return table.concat(lines, "\n")
            end
        -- END Compile --

        -- Write File --
            local function luaStr(v)
                if type(v) ~= "string" then return '""' end
                return string.format("%q", v)
            end

            local function syntaxError(src)
                if type(src) ~= "string" then return "compiler returned non-string" end
                local chunk, err
                if loadstring then
                    chunk, err = loadstring(src, "ms_macro_check")
                else
                    chunk, err = load(src, "@ms_macro_check", "t")
                end
                if chunk then return nil end
                return tostring(err)
            end

            local function brokenMacroSource(macroDef, errMsg)
                local b = macroDef.bind
                local bindLit = "nil"
                if type(b) == "table" and (b.type or b.key) then
                    local mods = {}
                    for _, m in ipairs(b.mods or {}) do mods[#mods + 1] = luaStr(m) end
                    bindLit = "{ type = " .. luaStr(b.type or "key")
                        .. ", key = " .. (b.key and luaStr(b.key) or "nil")
                        .. ", mods = { " .. table.concat(mods, ", ") .. " } }"
                end
                return "ms._brokenMacro({\n"
                    .. "    id    = " .. luaStr(macroDef.id) .. ",\n"
                    .. "    name  = " .. luaStr(macroDef.name or macroDef.id) .. ",\n"
                    .. "    group = " .. luaStr(macroDef.group or "visual") .. ",\n"
                    .. "    err   = " .. luaStr(errMsg) .. ",\n"
                    .. "    bind  = " .. bindLit .. ",\n"
                    .. "})"
            end

            ms.compiler._writeFile = function(sources, meta, outPath)
                meta = type(meta) == "table" and meta or {}
                local lines = {}
                lines[#lines + 1] = STAMP
                lines[#lines + 1] = "-- END AUTO-GENERATED --"
                lines[#lines + 1] = ""
                lines[#lines + 1] = "-- Creator Credits --"
                lines[#lines + 1] = "    ms.macroMeta = {"
                lines[#lines + 1] = "        name    = " .. luaStr(meta.name    or "Visual Macros") .. ","
                lines[#lines + 1] = "        version = " .. luaStr(meta.version or "1.0.0") .. ","
                lines[#lines + 1] = "        author  = " .. luaStr(meta.author  or "ms.compiler") .. ","
                lines[#lines + 1] = "        website = " .. luaStr(meta.website or "") .. ","
                lines[#lines + 1] = "    }"
                lines[#lines + 1] = "-- END Creator Credits --"
                lines[#lines + 1] = ""

                local function indentBlock(src)
                    local out = {}
                    for line in (src .. "\n"):gmatch("([^\n]*)\n") do
                        out[#out + 1] = line == "" and "" or (INDENT .. line)
                    end
                    return table.concat(out, "\n")
                end

                for _, entry in ipairs(sources) do
                    lines[#lines + 1] = "-- " .. entry.id .. " --"
                    lines[#lines + 1] = indentBlock(entry.source)
                    lines[#lines + 1] = "-- END " .. entry.id .. " --"
                    lines[#lines + 1] = ""
                end

                local out = table.concat(lines, "\n") .. "\n"

                os.execute("mkdir -p '" .. dataDir .. "'")

                local target = outPath or luaPath
                local f = io.open(target, "w")
                if not f then
                    error("ms.compiler: cannot open " .. target .. " for writing")
                end
                f:write(out)
                f:close()

                return true
            end
        -- END Write File --

        -- Rebuild --
            ms.compiler.rebuild = function()
                local f = io.open(jsonPath, "r")
                if not f then
                    error("ms.compiler.rebuild: cannot open " .. jsonPath)
                end
                local raw = f:read("*all")
                f:close()

                local ok, data = pcall(hs.json.decode, raw)
                if not ok or type(data) ~= "table" then
                    error("ms.compiler.rebuild: invalid JSON in " .. jsonPath .. ": " .. tostring(data))
                end

                ms.compiler._errors = {}

                local macros = data.macros or {}
                local sources = {}
                local count = 0

                for id, macroDef in pairs(macros) do
                    macroDef.id = id
                    local srcOk, src = pcall(ms.compiler.compile, macroDef)
                    local errMsg
                    if not srcOk then
                        errMsg = tostring(src)
                    else
                        errMsg = syntaxError(src)
                    end
                    if errMsg then
                        print("ms.compiler: compile error for '" .. id .. "': " .. errMsg)
                        ms.compiler._errors[id] = errMsg
                        src = brokenMacroSource(macroDef, errMsg)
                    end
                    sources[#sources + 1] = {
                        id     = id,
                        source = src,
                    }
                    count = count + 1
                end

                local functions = data.functions or {}
                local fnSources = {}
                local fnCount = 0
                for id, fnDef in pairs(functions) do
                    fnDef.id = id
                    local okF, srcF = pcall(ms.compiler.compileFunction, fnDef)
                    local fnErr
                    if not okF then
                        fnErr = tostring(srcF)
                    else
                        fnErr = syntaxError(srcF)
                    end
                    if fnErr then
                        print("ms.compiler: function compile error for '" .. id .. "': " .. fnErr)
                        ms.compiler._errors["fn:" .. id] = fnErr
                        srcF = "-- [FUNCTION COMPILE ERROR for " .. id .. "]\n"
                            .. "-- " .. fnErr:gsub("\n", "\n-- ") .. "\n"
                    end
                    fnSources[#fnSources + 1] = {
                        id     = "fn:" .. id,
                        source = srcF,
                    }
                    fnCount = fnCount + 1
                end
                table.sort(fnSources, function(a, b) return a.id < b.id end)

                table.sort(sources, function(a, b) return a.id < b.id end)

                local allSources = {}
                for _, s in ipairs(fnSources) do allSources[#allSources + 1] = s end
                for _, s in ipairs(sources)   do allSources[#allSources + 1] = s end
                ms.compiler._writeFile(allSources, data.meta)

                print("ms.compiler.rebuild: compiled " .. count .. " macro(s), "
                    .. fnCount .. " function tool(s) -> " .. luaPath)
                return count
            end
        -- END Rebuild --

        -- Load --
            ms.compiler.load = function()
                local prev = ms.compiler._registeredIds
                if prev then
                    for id in pairs(prev) do
                        if ms.registry then
                            ms.registry._defs[id] = nil
                            for i = #ms.registry._defList, 1, -1 do
                                if ms.registry._defList[i] == id then
                                    table.remove(ms.registry._defList, i)
                                end
                            end
                        end
                        if ms.bind and ms.bind._wires then ms.bind._wires[id] = nil end
                    end
                    ms.compiler._registeredIds = nil
                end

                local prevFn = ms.compiler._registeredFnIds
                if prevFn and ms.fn and ms.fn.registry then
                    for id in pairs(prevFn) do
                        ms.fn.registry._defs[id] = nil
                        for i = #ms.fn.registry._defList, 1, -1 do
                            if ms.fn.registry._defList[i] == id then
                                table.remove(ms.fn.registry._defList, i)
                            end
                        end
                    end
                    ms.compiler._registeredFnIds = nil
                end
                local _defBefore = {}
                if ms.registry then
                    for id in pairs(ms.registry._defs) do _defBefore[id] = true end
                end
                local _fnBefore = {}
                if ms.fn and ms.fn.registry then
                    for _, id in ipairs(ms.fn.registry._defList) do _fnBefore[id] = true end
                end

                if not hs.fs.attributes(luaPath) then
                    print("ms.compiler.load: no compiled file at " .. luaPath .. " (skipping)")
                    return false
                end

                local f = io.open(luaPath, "r")
                if not f then
                    print("ms.compiler.load: cannot open " .. luaPath)
                    return false
                end
                local rawSrc = f:read("*all")
                f:close()

                if not rawSrc:find(STAMP, 1, true) and hs.fs.attributes(jsonPath)
                    and pcall(ms.compiler.rebuild) then
                    local rf = io.open(luaPath, "r")
                    if rf then
                        rawSrc = rf:read("*all")
                        rf:close()
                    end
                end

                if ms.auditMacros then
                    local auditErrs = ms.auditMacros(rawSrc)
                    if #auditErrs > 0 then
                        local msg = "ms_macros_visual.lua failed security audit ("
                            .. #auditErrs .. " violation"
                            .. (#auditErrs > 1 and "s" or "") .. "):\n"
                        for _, e in ipairs(auditErrs) do
                            msg = msg .. "  - " .. e .. "\n"
                        end
                        print(msg)
                        ms.alert("Visual macros audit failed. See console.", 6)
                        return false
                    end
                end

                local sandbox = ms._macroSandbox
                if not sandbox then
                    error("ms.compiler.load: macro sandbox not initialized")
                end

                local chunk, loadErr
                if _VERSION and _VERSION >= "Lua 5.2" or not setfenv then
                    chunk, loadErr = load(rawSrc, "@ms_macros_visual.lua", "bt", sandbox)
                else
                    chunk, loadErr = loadstring(rawSrc, "@ms_macros_visual.lua")
                    if chunk then setfenv(chunk, sandbox) end
                end
                if not chunk then
                    print("ms.compiler.load: failed to load: " .. tostring(loadErr))
                    ms.alert("Visual macros load error. See console.", 6)
                    return false
                end

                ms._macroMetaLocked = ms._macroMetaFromHand == true
                ms._loadingVisual = true
                local ok, runErr = pcall(chunk)
                ms._loadingVisual = false
                ms._macroMetaLocked = false
                if not ok then
                    print("ms.compiler.load: execution error: " .. tostring(runErr))
                    ms.alert("Visual macros runtime error. See console.", 6)
                    return false
                end

                local reg = {}
                for _, id in ipairs(ms.compiler.list()) do
                    if not _defBefore[id] and ms.registry._defs[id] then reg[id] = true end
                end
                ms.compiler._registeredIds = reg

                local fnReg = {}
                if ms.fn and ms.fn.registry then
                    for _, id in ipairs(ms.fn.registry._defList) do
                        if not _fnBefore[id] then fnReg[id] = true end
                    end
                end
                ms.compiler._registeredFnIds = fnReg

                print("ms.compiler.load: visual macros loaded into sandbox")
                return true
            end
        -- END Load --

        -- Test Run --
            ms.compiler.testRun = function(macroDef, onDone)
                local reported = false
                local function done(ok, err)
                    if reported then return end
                    reported = true
                    if onDone then pcall(onDone, ok and true or false, err) end
                    return ok, err
                end

                if type(macroDef) ~= "table" then return done(false, "no macro definition") end
                local steps = macroDef.steps or {}
                local lines = {
                    "return function()",
                    indent(1) .. "local t = 100",
                }
                local prevMacroId = currentMacroId
                currentMacroId = type(macroDef.id) == "string" and macroDef.id or nil
                for _, step in ipairs(steps) do
                    local okc, line = pcall(emitStep, step, 1)
                    if not okc then
                        currentMacroId = prevMacroId
                        return done(false, "compile error: " .. tostring(line))
                    end
                    lines[#lines + 1] = line
                end
                currentMacroId = prevMacroId
                lines[#lines + 1] = "end"
                local src = table.concat(lines, "\n")

                if ms.auditMacros then
                    local errs = ms.auditMacros(src)
                    if errs and #errs > 0 then
                        return done(false, "audit failed: " .. tostring(errs[1]))
                    end
                end

                local sandbox = ms._macroSandbox
                if not sandbox then return done(false, "macro sandbox not initialized") end

                local chunk, loadErr = load(src, "@ms_test_run", "bt", sandbox)
                if not chunk then return done(false, "load: " .. tostring(loadErr)) end
                local ok, fnOrErr = pcall(chunk)
                if not ok then return done(false, tostring(fnOrErr)) end
                local fn = fnOrErr
                if type(fn) ~= "function" then return done(false, "compiled body is not a function") end

                local ctx = {
                    cancelled = false,
                    paused = false,
                    callStack = { "test:" .. (macroDef.id or "macro") },
                    onCancel = function() done(true) end,
                }
                local co = coroutine.create(function()
                    local rok, rerr = xpcall(fn, debug.traceback)
                    done(rok, rok and nil or rerr)
                end)
                if ms._coroContext then ms._coroContext[co] = ctx end
                if ms._activeContexts then ms._activeContexts[ctx] = true end

                local resok, reserr = coroutine.resume(co)
                if not resok then
                    return done(false, tostring(reserr))
                end
            end
        -- END Test Run --

        -- Write --
            ms.compiler.write = function(macroId, macroDef)
                assert(type(macroId) == "string", "ms.compiler.write: macroId must be a string")
                assert(type(macroDef) == "table",  "ms.compiler.write: macroDef must be a table")

                macroDef.id = macroId

                local data = { macros = {} }
                local f = io.open(jsonPath, "r")
                if f then
                    local raw = f:read("*all")
                    f:close()
                    local ok, parsed = pcall(hs.json.decode, raw)
                    if ok and type(parsed) == "table" then
                        data = parsed
                        data.macros = data.macros or {}
                    end
                end

                local bind = macroDef.bind
                if bind == nil then
                    local cfg = ms.bindConfig and ms.bindConfig[macroId]
                    if type(cfg) == "table"
                        and (cfg.type == nil or cfg.type == "key") and cfg.key ~= nil then
                        local mods = {}
                        for _, m in ipairs(cfg.mods or {}) do mods[#mods + 1] = m end
                        bind = {
                            type = "key",
                            key  = cfg.key,
                            mods = mods,
                        }
                    elseif type(data.macros[macroId]) == "table" then
                        bind = data.macros[macroId].bind
                    end
                end

                data.macros[macroId] = {
                    name     = macroDef.name,
                    author   = macroDef.author,
                    group    = macroDef.group,
                    bind     = bind,
                    steps    = macroDef.steps,
                    cooldown = macroDef.cooldown,
                    shared   = macroDef.shared,
                }

                os.execute("mkdir -p '" .. dataDir .. "'")
                local jf = io.open(jsonPath, "w")
                if not jf then
                    error("ms.compiler.write: cannot open " .. jsonPath .. " for writing")
                end
                jf:write(hs.json.encode(data, true))
                jf:close()

                ms.compiler.rebuild()

                print("ms.compiler.write: saved '" .. macroId .. "' to JSON and recompiled")
                return true
            end
        -- END Write --

        -- Delete --
            ms.compiler.delete = function(macroId)
                assert(type(macroId) == "string", "ms.compiler.delete: macroId must be a string")

                local f = io.open(jsonPath, "r")
                if not f then
                    print("ms.compiler.delete: no JSON file found")
                    return false
                end
                local raw = f:read("*all")
                f:close()
                local ok, data = pcall(hs.json.decode, raw)
                if not ok or type(data) ~= "table" then
                    error("ms.compiler.delete: invalid JSON")
                end

                data.macros = data.macros or {}
                if not data.macros[macroId] then
                    print("ms.compiler.delete: macro '" .. macroId .. "' not found")
                    return false
                end

                local deleted = data.macros[macroId]
                data.macros[macroId] = nil

                local pb = deleted and deleted.bind
                local pbType = (type(pb) == "table") and pb.type or nil
                local isConcrete = pbType == "key" or pbType == "mouse"
                    or pbType == "scroll" or pbType == "gamepad" or pbType == "combo"
                if isConcrete then
                    for _, def in pairs(data.macros) do
                        local b = def.bind
                        if type(b) == "table" and b.type == macroId then
                            local mods, seen = {}, {}
                            for _, mm in ipairs(pb.mods or {}) do
                                if not seen[mm] then
                                    seen[mm] = true
                                    mods[#mods + 1] = mm
                                end
                            end
                            for _, mm in ipairs(b.mods or {}) do
                                if not seen[mm] then
                                    seen[mm] = true
                                    mods[#mods + 1] = mm
                                end
                            end
                            def.bind = {
                                type      = pb.type,
                                key       = pb.key,
                                button    = pb.button,
                                buttons   = pb.buttons,
                                direction = pb.direction,
                                keys      = pb.keys,
                                mods      = mods,
                            }
                        end
                    end
                end

                local jf = io.open(jsonPath, "w")
                if not jf then
                    error("ms.compiler.delete: cannot write JSON")
                end
                jf:write(hs.json.encode(data, true))
                jf:close()

                ms.compiler.rebuild()
                print("ms.compiler.delete: removed '" .. macroId .. "' and recompiled")
                return true
            end
        -- END Delete --

        -- List --
            ms.compiler.list = function()
                local f = io.open(jsonPath, "r")
                if not f then return {} end
                local raw = f:read("*all")
                f:close()
                local ok, data = pcall(hs.json.decode, raw)
                if not ok or type(data) ~= "table" or type(data.macros) ~= "table" then
                    return {}
                end
                local ids = {}
                for id in pairs(data.macros) do ids[#ids + 1] = id end
                table.sort(ids)
                return ids
            end

            ms.compiler.entries = function()
                local f = io.open(jsonPath, "r")
                if not f then return {} end
                local raw = f:read("*all")
                f:close()
                local ok, data = pcall(hs.json.decode, raw)
                if not ok or type(data) ~= "table" or type(data.macros) ~= "table" then
                    return {}
                end
                local out = {}
                for id, def in pairs(data.macros) do
                    local name = type(def) == "table" and def.name
                    out[#out + 1] = {
                        id   = id,
                        name = (type(name) == "string" and name ~= "") and name or id,
                    }
                end
                table.sort(out, function(p, q)
                    local a, b = p.name:lower(), q.name:lower()
                    if a ~= b then return a < b end
                    return p.id < q.id
                end)
                return out
            end
        -- END List --

        -- Get --
            ms.compiler.get = function(macroId)
                local f = io.open(jsonPath, "r")
                if not f then return nil end
                local raw = f:read("*all")
                f:close()
                local ok, data = pcall(hs.json.decode, raw)
                if not ok or type(data) ~= "table" or type(data.macros) ~= "table" then
                    return nil
                end
                local def = data.macros[macroId]
                if def then def.id = macroId end
                return def
            end
        -- END Get --

        -- Function tools (data.functions) --
            local function readData()
                local data = {}
                local f = io.open(jsonPath, "r")
                if f then
                    local raw = f:read("*all")
                    f:close()
                    local ok, parsed = pcall(hs.json.decode, raw)
                    if ok and type(parsed) == "table" then data = parsed end
                end
                data.macros    = data.macros    or {}
                data.functions = data.functions or {}
                return data
            end

            local function writeData(data)
                os.execute("mkdir -p '" .. dataDir .. "'")
                local jf = io.open(jsonPath, "w")
                if not jf then
                    error("ms.compiler: cannot open " .. jsonPath .. " for writing")
                end
                jf:write(hs.json.encode(data, true))
                jf:close()
            end

            ms.compiler.writeFunction = function(fnId, fnDef)
                assert(type(fnId) == "string" and fnId:match("^[%a_][%w_]*$"),
                    "ms.compiler.writeFunction: fnId must be a valid identifier")
                assert(type(fnDef) == "table", "ms.compiler.writeFunction: fnDef must be a table")
                if ms.compiler.get(fnId) then
                    error("ms.compiler.writeFunction: '" .. fnId
                        .. "' collides with a macro of the same id")
                end
                local data = readData()
                data.functions[fnId] = {
                    name      = fnDef.name,
                    steps     = fnDef.steps,
                    coroutine = fnDef.coroutine == true,
                }
                writeData(data)
                ms.compiler.rebuild()
                pcall(ms.compiler.load)
                print("ms.compiler.writeFunction: saved '" .. fnId .. "' and recompiled")
                return true
            end

            ms.compiler.deleteFunction = function(fnId)
                assert(type(fnId) == "string", "ms.compiler.deleteFunction: fnId must be a string")
                local data = readData()
                if not data.functions[fnId] then
                    print("ms.compiler.deleteFunction: '" .. fnId .. "' not found")
                    return false
                end
                data.functions[fnId] = nil
                writeData(data)
                ms.compiler.rebuild()
                pcall(ms.compiler.load)
                print("ms.compiler.deleteFunction: removed '" .. fnId .. "'")
                return true
            end

            ms.compiler.listFunctions = function()
                local data = readData()
                local out = {}
                for id, def in pairs(data.functions) do
                    out[#out + 1] = {
                        id   = id,
                        name = def.name or id,
                    }
                end
                table.sort(out, function(a, b) return a.id < b.id end)
                return out
            end

            ms.compiler.getFunction = function(fnId)
                local data = readData()
                local def = data.functions[fnId]
                if def then def.id = fnId end
                return def
            end
        -- END Function tools --

        -- Meta (pack credits: name / author / website) --
            local META_FIELDS = {
                "name",
                "version",
                "author",
                "website",
            }

            local function readJsonMeta()
                local f = io.open(jsonPath, "r")
                if not f then return {} end
                local raw = f:read("*all")
                f:close()
                local ok, data = pcall(hs.json.decode, raw)
                if not ok or type(data) ~= "table" or type(data.meta) ~= "table" then
                    return {}
                end
                return data.meta
            end

            ms.compiler.getMeta = function()
                local hand = ms._macroMetaHand or {}
                local stored = readJsonMeta()
                local out = {
                    locked = {},
                }
                local claimed = 0
                for _, field in ipairs(META_FIELDS) do
                    if hand[field] then
                        out[field] = hand[field]
                        out.locked[field] = true
                        claimed = claimed + 1
                    else
                        out[field] = type(stored[field]) == "string" and stored[field] or ""
                    end
                end
                out.owned = claimed == #META_FIELDS
                return out
            end

            ms.compiler.setMeta = function(meta)
                assert(type(meta) == "table", "ms.compiler.setMeta: meta must be a table")

                local hand = ms._macroMetaHand or {}
                local stored = readJsonMeta()

                local data = { macros = {} }
                local f = io.open(jsonPath, "r")
                if f then
                    local raw = f:read("*all")
                    f:close()
                    local ok, parsed = pcall(hs.json.decode, raw)
                    if ok and type(parsed) == "table" then
                        data = parsed
                        data.macros = data.macros or {}
                    end
                end

                data.meta = {}
                for _, field in ipairs(META_FIELDS) do
                    local src = hand[field] and stored or meta
                    data.meta[field] = type(src[field]) == "string" and src[field] or ""
                end

                os.execute("mkdir -p '" .. dataDir .. "'")
                local jf = io.open(jsonPath, "w")
                if not jf then
                    error("ms.compiler.setMeta: cannot open " .. jsonPath .. " for writing")
                end
                jf:write(hs.json.encode(data, true))
                jf:close()

                ms.compiler.rebuild()
                print("ms.compiler.setMeta: updated pack meta and recompiled")
                return true
            end
        -- END Meta --

        -- Paths --
            ms.compiler.paths = {
                json = jsonPath,
                lua  = luaPath,
                data = dataDir,
            }

            ms.compiler.repoint = function()
                dataDir = ms.profile.path("data")
                jsonPath = ms.profile.file("visualJson")
                luaPath = ms.profile.file("visualLua")
                ms.compiler.paths.json = jsonPath
                ms.compiler.paths.lua = luaPath
                ms.compiler.paths.data = dataDir
            end
        -- END Paths --
    end
-- END ms_compiler --
