-- AUTO-GENERATED by ms.compiler (DO NOT EDIT BY HAND) --
-- Source: data/ms_macros_visual.json
-- Rebuild: ms.compiler.rebuild()
-- END AUTO-GENERATED --

-- Creator Credits --
    ms.macroMeta = {
        name    = "Visual Macros",
        version = "1.0.0",
        author  = "ms.compiler",
        website = "",
    }
-- END Creator Credits --

