-- AUTO-GENERATED by ms.compiler (DO NOT EDIT BY HAND) --
-- Source: data/ms_macros_visual.json
-- Rebuild: ms.compiler.rebuild()
-- END AUTO-GENERATED --

-- Creator Credits --
    ms.macroMeta = {
        name    = "Visual Macros",
        version = "1.0.0",
        author  = "ms.compiler",
        website = "",
    }
-- END Creator Credits --

-- Test_Macro --
local Test_MacroFunction = ms.fn(function()
    local t = 100
    ms.alert("Running macro.", 3)
    ms.press("a")
    ms.wait(96)
    ms.release("a")
    ms.wait(114)
    ms.press("s")
    ms.wait(100)
    ms.release("s")
    ms.wait(140)
    ms.press("d")
    ms.wait(91)
    ms.release("d")
    ms.wait(144)
    ms.press("f")
    ms.wait(88)
    ms.release("f")
    ms.alert("Macro run complete.", 3)
end, "Test Macro")

ms.bind.define("Test_Macro", Test_MacroFunction, {
    group   = "visual - main",
    label   = "Test Macro",
})
-- END Test_Macro --

