-- AUTO-GENERATED by ms.compiler v3 (DO NOT EDIT BY HAND) --
-- END AUTO-GENERATED --

-- Creator Credits --
    ms.macroMeta = {
        name    = "Visual Macros",
        version = "1.0.0",
        author  = "ms.compiler",
        website = "",
    }
-- END Creator Credits --

